'use client'
import { useState } from 'react'
import type { Subscriber } from '@/lib/communications'
import { adminRequest } from './api'
export default function SubscriberManager({initialSubscribers}:{initialSubscribers:Subscriber[]}) {
  const [subscribers,setSubscribers]=useState(initialSubscribers),[status,setStatus]=useState('active'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const filtered=subscribers.filter(row=>(!status||row.status===status)&&row.email.toLowerCase().includes(search.toLowerCase()))
  async function change(row:Subscriber,remove:boolean){if(!window.confirm(remove?`Permanently delete ${row.email}'s subscription record?`:`Unsubscribe ${row.email}?`))return;setBusy(true);setError('');setMessage('');try{await adminRequest('/api/admin/subscribers',{method:remove?'DELETE':'PATCH',body:JSON.stringify({id:row.id})});setSubscribers(current=>remove?current.filter(item=>item.id!==row.id):current.map(item=>item.id===row.id?{...item,status:'unsubscribed',unsubscribedAt:new Date().toISOString()}:item));setMessage(remove?'Subscription record deleted.':'Subscriber unsubscribed.')}catch(error){setError(error instanceof Error?error.message:'Update failed.')}finally{setBusy(false)}}
  return <><h1>Newsletter subscribers</h1><p className="admin-muted">Manage consented subscriptions and export the active mailing list.</p>{error&&<p className="admin-error" role="alert">{error}</p>}{message&&<p className="admin-notice" role="status">{message}</p>}<div className="admin-panel admin-grid"><div className="admin-field"><label htmlFor="subscriber-search">Search email</label><input id="subscriber-search" type="search" value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="admin-field"><label htmlFor="subscriber-status">Status</label><select id="subscriber-status" value={status} onChange={event=>setStatus(event.target.value)}><option value="active">Active</option><option value="unsubscribed">Unsubscribed</option><option value="">All subscribers</option></select></div></div><div className="admin-actions"><a className="admin-button-secondary" href={`/api/admin/subscribers?export=csv&status=${status}`}>Export selected status to CSV</a><span>{filtered.length} subscribers</span></div><section className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>Email</th><th>Status</th><th>Consent recorded</th><th>Unsubscribed</th><th>Actions</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td>{row.email}</td><td>{row.status}</td><td>{new Date(row.consentedAt).toLocaleString()}</td><td>{row.unsubscribedAt?new Date(row.unsubscribedAt).toLocaleString():'—'}</td><td><div className="admin-actions">{row.status==='active'&&<button type="button" className="admin-button-secondary" disabled={busy} onClick={()=>change(row,false)}>Unsubscribe</button>}<button type="button" className="admin-button-secondary" disabled={busy} onClick={()=>change(row,true)}>Delete record</button></div></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-4">No matching subscribers.</p>}</section></>
}
